### ISSUE TITLE
File select (open) dialogue is broken.

### ISSUE THREAD

**Issue by dbanet** [bitwiseworks/mozilla-os2#108]
Apparently, FF31 uses its own XUL file select dialogue instead of a system one.

To reproduce, press ``Control-O``.
The following unusable dialogue window appears:

![Broken file select (open) dialgoue screenshot.](https://clbin.com/jCa2dD.png)

The same dialogue is used for file selection for ``<input type="file" />`` HTML forms.

**Comment by dryeo** [comment]
Interesting, I saw a similar (non-working) file dialog when I first ran 
Thunderbird 31.6 from dist/bin but after packaging and installing I get 
a regular OS/2 file dialog.
My slightly older build of Firefox 31.6 also has a normal OS/2 file 
dialog when pressing ctrl-o

**Comment by dmik** [comment]
Thanks for pointing that out. I confirm. I will look what they changed there. I wonder if we should leave the XUL dialog (after making it work of course) instead of the native OS/2 dialog. Opinions?

**Comment by dbanet** [comment]
Native one.

The default (old) OS/2 dialogue sucks indeed, but eCS2.2b2 is bundled with an alternative one made by eCoSoft. Although there are some drawbacks, it's pretty good. Yeah, it's closed-source, but my point is that we can write a better replacement, or turn FOSS and improve eCoSoft's one, and since it is a system component replacement, it will affect all applications that do not use their own dialogue. Even more, I think Qt4 should also use system's dialogue if that is possible.

**Comment by dmik** [comment]
Yes, my question was with Qt in mind, indeed. The problem with the eCS 2.2 dialogue is that it's closed source, yes. And I have a guess that it will behave badly when there are, say, 10 thousand files in a directory (in Qt I specifically made sure this works flawlessly, I even demonstrated it once at WSE). The other problem was the look and feel but we only had the standard old OS/2 open dialog back then, the one in eCS 2.2 is way better of course.

**Comment by dbanet** [comment]
All that brings us back to the fact that WPS is actually very bad at file management, which includes file select dialogues.

The old native OS/2 dialogue was not built on top of WPS (I actually suppose it was implemented even before WPS, and hasn't changed since then), while the eCoSoft's one uses it I suppose (I can see tree and detail views in it, which are WFolders, I suppose?).

It would be a hard way to make WPS good at file management and, generally, meet modern requirements, and one way, I suppose, would be to wholly rewrite WFolder, as, I suppose, WFolder is the class that actually draws all the files-objects-folders GUI. With Qt.

But first one has to figure out how to use GCC, Qt and SOM together. :)

If one claims the above is nonsense, I'd reply writing separate file select dialogues (without WPS in mind) for each application (Lotus, PMView, XUL, Qt, Odin (Java), lots of them) is much more nonsense, and not an OS/2-way.

**Comment by dryeo** [comment]
On 06/29/15 03:35 AM, Dmitriy Kuminov wrote:
> Thanks for pointing that out. I confirm. I will look what they changed
> there.

Really seems to be a packaging thing. Using FF built from master and the 
patches from KOMH, I get the XUL dialog when running Firefox from 
dist/bin but when unzipping the package, I get the usual OS/2 dialog

**Comment by dmik** [comment]
Okay, I found it out. The thing is that there are two implementations of the `@mozilla.org/filepicker;1` component: one is pure (generic) JS (`toolkit/components/filepicker/nsFilePicker.js`) and another one is native C++ (`widget/<platform>/nsFilePicker.cpp`). The pure JS was mistakenly deployed on OS/2 and would obscure the native one — but only in the development builds because the packing stage of Firefox already excludes it on OS/2, or, to be precise, it is only included for GTK targets. Actually, this is an inconsistency of the Mozilla build system: in one place they do `use it if target is not (A, B, C)` in another place they do `use it if target is E`. If the former place were done as the latter one we would not have experienced this problem at all.

The fix is in 2c920e83abdc9d3a2c178695caf347fb773915b4. You need to run `make build` from the build root (to regenerate python makefiles and such) and then manually remove `dist/bin/components/nsFilePicker.js` and ``dist/bin/components/nsFilePicker.manifest` to get rid of this generic JS dialog.
