### ISSUE TITLE
Open in new tab does not always work

### ISSUE THREAD

**Issue by StevenLevine** [bitwiseworks/mozilla-os2#125]
This appears to be a regression from 24.8.1.  Opening a URL from the command line used to open the URL in a new tab.  Now it always opens in a new window, even if the -new-tab switch is present.  The same is true if Open in new tab is selected from the bookmarks (aka LIbrary) notebook context menu.

**Comment by dmik** [comment]
Steve, do you have a linux/windows around? To check how it behaves there.

**Comment by StevenLevine** [comment]
>Steve, do you have a linux/windows around? To check how it behaves there.

Already did that or I would not reported it.  Also tested with fresh
profile.  The current Linux build that I have installed (probably 39.x)
behaves as expected and honors the command line switches as expected.

**Comment by dmik** [comment]
Okay, thanks. I will check it then.

**Comment by wztest** [comment]
I also just discovered the same problem, its not working with the -new-tab parameter and will always open the url in a new window and not in the already running Firefox window that is open.  No MOZ_NO_REMOTE set and as Steve said its working on other platforms (here on win).

**Comment by LewisR** [comment]
FWIW, this does seem to work correctly in SM 2.28 (tested opening a url object from my Websites folder; this opened a new tab in my current browser window, as expected).

**Comment by SilvanScherrer** [comment]
When you open Firefox and hit the restore previous session, it also opens several instances.

**Comment by wztest** [comment]
I have the same behavior here, it opens a new windows with the start page and the 'main' window that has all tabs from the previous session.

**Comment by wztest** [comment]
Somehow it stopped after several starts when the 2nd window was visible in the restore session page and there it could be deselected and it is now starting with only one window.

**Comment by wztest** [comment]
Now its back again: 2 windows after restoring the previous session.

**Comment by wztest** [comment]
Beta 6 (ESR38) doesn't change this behavior, -new-tab will always open a new window and not a new tab in the 'main' window.

**Comment by dmik** [comment]
#161 may some how be related to this, putting it here to create a link, this is a wild guess so far.

**Comment by dmik** [comment]
I finally confirm the problem, trying to catch its traces in the logs.

**Comment by dmik** [comment]
There seems to be several issues in this area (they are mostly related to the fact that a lot of processing went from C++ to .js and this includes command line parsing). First, command line handling is not correct per se. If you try to start a second instance of firefox, no matter which arguments you give, it will act as if you gave it a single `"klibc"` argument (this is a secret parameter that kLIBC passes last to kLBC based executables started with exec()). This, for example, takes place if you start firefox.exe from sh.exe (as in my test environment).

Second, the `_openURIInNewTab` function (defined in browser.js) seems to never be called for some reason. I will solve the command line problem first and then find out that reason.

**Comment by dmik** [comment]
Something strange is happening there. There is a new class, `nsWindowMediator`, that is used now to track top-level windows. The new tab code eventually uses it to find an appropriate top-level window to open a tab but this this search always fails here (returns "no window"). The problem is that I don't see any code path that would initialize the required variables (in particular,  nsWindowMediator::mTopLevelWindow) to make this search succeed. I wonder how it can work on other platforms because this code is purely cross-platform... I miss something. I will have to make an OS X build of Firefox to see what's happening there.

**Comment by dmik** [comment]
From what I see, the `nsWindowListener::ZLevelChanged` callback is not called on OS/2 when the Z-position of the window changes. Hence, no `mTopLevelWIndow` update in `nsWindowMediator` through `SetZPositon` as Windows and OS X do. This whole `ZLevelChanged` code was added by this changeset https://hg.mozilla.org/mozilla-central/rev/448410c2035e which happened right after v17 but before v24, hence it's a 24+ regression. I need to implement this notification on OS/2.

**Comment by dmik** [comment]
The issue is completely gone now, opening external links in new tabs works well now as well as session restore (no more new windows -- all tabs are opened in the same window as they should). Opening from the bookmarks window to a new tab works fine too. Note that this change may also fix other similar problems.

For the klibc exec() case, I created a separate issue, #168.
