### ISSUE TITLE
Scrolling in some newspaper gives 100 % CPU load

### ISSUE THREAD

**Issue by EinarLygre** [bitwiseworks/mozilla-os2#126]
When scrolling in DB.no (newspaper) it again and again gives 100% CPU load with the time glass showing up. After some time (5 -30 sec) I can scroll further. At the same time some advertisements in the paper are displayed only with the HTML-code. The same problem is found in other newspapers, but not in all.
The image shows an example and the CPU-meter shows the CPU load. 
![Uploading Captured001.jpg…]()
After having scrolled through the whole page the scrolling up and down is normal, but the HTML code is still displayed. 
In win8 there is no such problems.

**Comment by dbanet** [comment]
Tried restarting Firefox? I suspect it is related to #55.

What is your hardware? A slow CPU will give lags on scrolling: today's browsers are complex and CPU-intensive, but Firefox on OS/2 is (from my experience) up to two-three times slower than on Windows. Combined with #55 it will give an awfully unacceptable performance after a day of usage.

P. S. Your screenshot hasn't been loaded. Please retry giving it more time (check it displays in the "Preview" tab).

**Comment by EinarLygre** [comment]
![Uploading Captured001.jpg…]()
![Uploading Captured001.jpg…]()

**Comment by dmik** [comment]
@EinarLygre again, you were not patient enough to wait until your JPG is uploaded. Please do NOT press the Comment button until you see your uploaded image on the Preview tab. It's also not clear why you closed this issue. Please clarify.

**Comment by EinarLygre** [comment]
On 31.07.15 13:39, Dmitriy Kuminov wrote:
>
> @EinarLygre <https://github.com/EinarLygre> again, you were not 
> patient enough to wait until your JPG is uploaded. Please do NOT press 
> the Comment button until you see your uploaded image on the Preview 
> tab. It's also not clear why you closed this issue. Please clarify.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/bitwiseworks/mozilla-os2/issues/126#issuecomment-126662836>.
>

Well, this is ridiculous. I wrote an answer in GitHub and ended up with 
a FF-crash.  When I opened the Preview tab it displayed the message 
Uploading preview.... Returning to the first tab ended in a crash. And 
now I can't open FF!!  I probably have to reboot.

Here is what I wrote:

/1. I have a 3.34 GHz intel Core 2 Duo CPU and the boot disk with FF is 
a SDD 250 GB. My network is fiber with 50 Mbps up and down.//
//2. I were patient enough. I tried to upload the JPG file last night. 
The process lasted for 8 hours and nothing happened. I am going to send 
the JPG file by email.//
//3.  I have  also tried the Dooble browser and everything works OK. The 
HTML code is never displayed  but the images meant to be displayed is 
normally displayed./

EinarLygre

**Comment by dmik** [comment]
Something strange is happening on your system. What is the value of VIRTUALADDRESSLIMIT in your CONFIG.SYS? You may experiencing some out of memory issues (see #55 for some info). Also it may give you 100% CPU load due to Flash located on that page. Please disable Flash and check if it changes anything.

**Comment by dmik** [comment]
Uploading also works fine here, this is the site you are experiencing problems with if I get it right:
![test](https://cloud.githubusercontent.com/assets/900726/9012412/92a8fd24-37c5-11e5-8e3c-db0a87afd3e1.png)

Scrolling works fine here. If I play a lot with it I sometimes get a popup message about an unresponsive script (some heavy JS work on that site, it's badly designed, to my taste, constant page refreshes etc) but I just dismiss it and all works fine again.

**Comment by LewisR** [comment]
Scrolling works well here, both under FF and under SM on OS/2 (latest builds). Tested manual scrolling (via the scrollbar) and auto-scroll (MMB, then downward gesture on the TrackPoint). Note also that the site felt responsive (not the current "responsive," as in adaptive to different devices and screen geometries, but responsive as in "little delay") even on my ThinkPad T43, which is a single core 2GHz Dothan CPU with 2GB RAM under SNAP (video is ATI X300).

I am also using the following in my startup scripts:

SET NSPR_OS2_NO_HIRES_TIMER=1
SET MOZ_ACCELERATED=0
SET MOZ_NO_RWS=1
SET MOZ_DISABLE_OOP_TABS=1

(I use MOZ_ACCELERATED=0 to clean up mouse artifacts which are otherwise present on the screen, but this may be worth trying in this case to see if the system load eases.)

I, too, noticed heavy JS, as well as web fonts pulled from Google, and loads of Akamai junk (typical for news sites). I specifically did *not* enable my local Privoxy to block that stuff for this test.

**Comment by dbanet** [comment]
Khm. @EinarLygre, your PC appears to be fast enough for the web browser to operate the web page rapidly enough, hence I second @dimk: something is wrong with your environment.

P. S. E-Mail attachments are not functional here on GitHub Issues. You may try uploading a screenshot to [an image hosting](http://imgur.com/), but I personally doubt it will be of any help.

**Comment by EinarLygre** [comment]
file:///F:/A-key/Captured001.jpg

**Comment by EinarLygre** [comment]
file:///F:/A-key/Captured001.jpg
This is a new message for me. I understand it as uploading of the jpg-file works. I have rebooted, but I also realize that I used the 24 version of FF when I tried uploading the file.

**Comment by dmik** [comment]
@EinarLygre your comments still don't contain the picture (the best way for you to put it here is not dragging but pressing the "selecting them" text at the bottom of the comment field so that a file open dialog shows up where you select the image to upload). Please also try to do what is suggested by @LewisR and me to see if it helps you with this site.

**Comment by EinarLygre** [comment]
![captured003](https://cloud.githubusercontent.com/assets/13570829/9023495/310fd266-389e-11e5-8469-19c4b102c8a2.jpg)
![captured004](https://cloud.githubusercontent.com/assets/13570829/9023499/4187d828-389e-11e5-8de7-eaa3bc6d4578.jpg)
At last!   This time I reduced the size of the images and the uploading was done quickly.
I think I have to make the problem more clearly:
The scrolling problem is only a symptom for something else. The problem is the heavy CPU load when some of the images on the page is to be displayed. During this load I can't do anything, neither scrolling or anything else. When the process ends the place for the image is replaced with HTML code (I believe). This can take up to 30 sec. The first image shows this. In this specific instant the heavy load lasted for about 7 sec. You can see this in the CPU meter.
The next image shows how it should be. I just pressed the reload symbol and the correct image was displayed. This time it took a couple of sec. shorter time.
In this site (dagbladet.no), this happens every time and at different places and takes different  time. But I also see it in other sites, even BBC.com, but it is not so common.

**Comment by SilvanScherrer** [comment]
did this behaviour change with ffox 38?

**Comment by EinarLygre** [comment]
Hi.
I don't know. I get the message: "The application has been updated, but 
your version of SQLite is too old and the application cannot run"
The version of sqlite is 3.7.2-5

**Comment by dmik** [comment]
Most likely you have another version of mozsql.dll loaded in memory (i.e. another version of Firefox or Seamonkey or Thunderbird is running). Please reboot and try to only start the new Firefox.

**Comment by SilvanScherrer** [comment]
is this still the case with Firefox 45?

**Comment by EinarLygre** [comment]
I haven't installed FF 45 yet and anyway the problem has disappeared in FF 38.8.0 that I now use
