### ISSUE TITLE
38ESR Fontconfig error

### ISSUE THREAD

**Issue by wztest** [bitwiseworks/mozilla-os2#160]
Firefox doesn't start here because of a fontconfig error:

Fontconfig error: Cannot load default config file
VMI_CMD_SETPTR - rc= 0  ulStatus= 1
Video driver is SNAP - mouse ptr will not be hidden
Unable to enable DIVE - it will not be used for this session
Fontconfig error: Cannot load default config file
Fontconfig error: Cannot load default config file
Fontconfig error: Cannot load default config file
Fontconfig error: Cannot load default config file
Fontconfig error: Cannot load default config file
Fontconfig error: Cannot load default config file
Fontconfig error: Cannot load default config file

It looks like it can't find the fonts.conf file. I have a cmd file to start firefox and this one sets the unixroot var which points to a dir that has \ETC\fonts.conf

**Comment by dryeo** [comment]
On 02/27/16 02:08 PM, wztest wrote:
> It looks like it can't find the fonts.conf file. I have a cmd file to
> start firefox and this one sets the unixroot var which points to a dir
> that has \ETC\fonts.conf

As a workaround, try SET FONTCONFIG_FILE=x;/etc/fonts.conf
or correctly install fonts.conf in /etc/fonts and test and if needed SET 
FONTCONFIG_PATH=x:/etc/fonts

**Comment by wztest** [comment]
Thanks for the help, using the first set with a static path to etc dir and the set for the fonts dir fixed the start issue and the browser is up and running. 
It now created some files in the fonts cache dir. How is the new font search and find working? The UI and rendering font is now different compared to the previous firefox version 24. When I check in Options/Fonts & Colors/Advanced the only difference is Latin.

**Comment by SilvanScherrer** [comment]
we will add those hints to the readme.

**Comment by wztest** [comment]
As an example the hobbes start page:

**Firefox24:**
![esr24hobbespart](https://cloud.githubusercontent.com/assets/6126421/13407694/103ce65e-df2a-11e5-9d3b-de9f4023caef.png)

**Firefox38:**
![esr38hobbespart](https://cloud.githubusercontent.com/assets/6126421/13407735/472dbaee-df2a-11e5-8f76-5cf129e1068b.png)

**Comment by SilvanScherrer** [comment]
You miss some fonts.conf stuff. If not installed by rpm you have to look carefully at the zip. There are some other config files.

**Comment by dmik** [comment]
@wztest, the OS/2 port of fontconfig has integration with the PM system fonts list (it will automatically pick up any change to that list for all supported font formats, like TTF and Type1). This is done with this special entry in the default `fonts.conf`: `<dir>OS2FONTDIR</dir>` (which is enough for most users). Other than that, it's a fully functional fontconfig port and you can read its official manual to get information about customizing it to your needs.

As @SilvanScherrer mentioned, there are some more default config files that affect the behavior, and they are stored in `/etc/fonts/conf.d`. One of special importance on OS/2 is `30-warpsans.conf` which is needed to use `Workplace Sans` TTF instead of WarpSans which is proprietary OS/2 binary font format and hence not supported by fontconfig. Note that `/etc/fonts/conf.d/30-warpsans.conf` is actually a symlink to `/usr/share/fontconfig/conf.avail/30-warpsans.conf`so in order to have everything working properly you need to extract all the files from `fontconfig-2_11_94-1_oc00.zip` and properly set up your UNIXROOT. We will update README.OS2 with this.

In the mean time, here is how hobbes looks here with FF 24 and FF 38 with the default OS/2 Type1 font set:

FF 24:
![2016-03-01 13 59 10](https://cloud.githubusercontent.com/assets/900726/13425268/c1ef754c-dfb6-11e5-9f86-1c1bcc8faa3a.png)

FF 38:
![2016-03-01 14 05 02](https://cloud.githubusercontent.com/assets/900726/13425271/c4c354be-dfb6-11e5-9546-52ae3346f67f.png)

It looks like the default fontconfig substitution more or less correctly picks up the `Times New Roman` Type1 font for regular serif, but it fails to do so for bold and italic serif (from what I see `Workplase Sans` TTF gets selected). This needs some investigation and will be done as part of #146.

Anyway, if you install modern TTF fonts (like the web fonts from Microsoft or the Bookman family and friends installed by AOO or the DejaVu family which is a de-facto standard in the Linux world and which fontconfig has a good set up for), you will get a pretty nice view in FF 38, like this:

![2016-03-01 14 01 34](https://cloud.githubusercontent.com/assets/900726/13425410/a487be78-dfb7-11e5-94e6-a323997e2fc9.png)

**Comment by wztest** [comment]
Thanks for some explanations,  I do have only Workplase Sans TTF as an additional font installed. The setup and use of %UNIXROOT% was not working here. When OS2FONTDIR is the link to \PSFONTS it was done to have an auto update mechanism when file will change in this dir, when i will just enter C:\PSFONTS it will act in a different way? Fontconfig will get the path for OS2FONTDIR from PM (ini,reg)?

**Comment by dmik** [comment]
If you put C:\PSFONTS, it will only pick up fonts from that directory. Any other fonts installed in PM (or via XWP) located in different directories won't be picked up. OS2FONTDIR is not a link to \PSFONTS, it picks up all fonts installed through PM directly from the PM registry (by reading their actual paths).
