### ISSUE TITLE
38.8.0 for OS/2 Beta 7 conflicts with AOO

### ISSUE THREAD

**Issue by rbri** [bitwiseworks/mozilla-os2#173]
There seems to be a library conflict between the latest FF and AOO.

FF requires libicu.i686
AOO requires libicu.i386

Is there an chance to sync this. At the moment i have to switch to the old lib (more or less simple with yum) before i can start AOO and switch back for FF.

Thanks for doing all the work with FF and AOO.

**Comment by dmik** [comment]
Thanks for reporting! Strictly speaking, there is no conflict. Since we made new `libicu` packages providing an incompatible set of DLLs publicly available, even doing `yum update` will make AOO lack the old DLLs (i.e. it has nothing to do with Firefox per se). You need to install the `libicu-legacy` package to make AOO happy. Please report if doing so helps you.

**Comment by SilvanScherrer** [comment]
We also do an official announcement of all this on monday.

**Comment by rbri** [comment]
Thanks for the super fast answer. Did some tests with libicu-legacy and everything works fine again.
You can close this issue.

**Comment by dmik** [comment]
Thanks for testing. This is a one time thingy and we will make such an update automatically happen in the future.

**Comment by StevenLevine** [comment]
This is a known issue.  I don't have access to the issues page at the
moment, but search for -legacy in the recent issues and you will find the
name of the rpm package that resoves this.

**Comment by LewisR** [comment]
Actually, Steve, that was this issue, and the package is libicu-legacy.

Funny, I actually bumped into this one over the weekend while updating my brother's ThinkPad. LOL
