### ISSUE TITLE
Firefox 38.8.0, postscript printer, no eCUPS, print.os2.postscript.use_builtin set, it prints !

### ISSUE THREAD

**Issue by lerdmann** [bitwiseworks/mozilla-os2#175]
regarding Firefox 38.2.1/38.8.0, also Thunderbird 31.8.0:

I have a postscript printer and native printing support installed (PSCRIPT driver, printing to an SLPR port, I also set up an alternative printer object printing to a USB port).
I have eCS 2.2 beta1 installed and therefore CUPS is also installed with the deamon running in the background. Nonetheless I have no printer object printing to an eCUPS port.

I thought it would not work but I just set "print.os2.postscript.use_builtin" = true and gave printing a try, printing to the printer object attached to the SLPR port. And it worked ! 

Could that be expected ? From the readme I had understood that you HAVE to print via eCUPS in any case. But for native postscript printers this seems not to be necessary. I guess this would be worth mentioning in the README.OS2 file.

**Comment by SilvanScherrer** [comment]
this also goes along with #170 and #171

**Comment by dspiatkowski** [comment]
Quick comment, I too am in a situation similar to what Lars is reporting, where my Brother HL5470dw native Postscript printer works. In addition to being able to print using the "print.os2.postscript.use_builtin= true" config the jobs also appear to support the native PS driver options such as DUPLEX printing, etc. This appears to be contrary to what the README states...not complaining (LOL), just providing some feedback on what I'm actually seeing.

On the other hand, and this is a bit of a surprise, what does not appear to work is the built-in PDF printing support.

**Comment by dmik** [comment]
Tested things a bit while working on #231, #171 and rest. The meaning of `print.os2.postscript.use_builtin` is as follows. When `true`, it will force Firefox to use a Cairo PS surface to generate raw Postscript data which is then sent directly to the printer's spooler instead of a special Cairo OS/2 surface that paints on a printer's HDC using GPI primitives. This obviously requires a native printer driver that understands postscript (i.e. has a CAPS_TECH_POSTSCRIPT type) so for drivers of all other types this setting is simply ignored (has no effect). CUPS itself is not involved here at all because FF will talk directly to the printer's spooler in PM_Q_RAW mode. Given that PSCRIPT.DRV (obviously) identifies itself as CAPS_TECH_POSTSCRIPT, everything works nicely for printers using this driver as soon as `print.os2.postscript.use_builtin` is set to `true` (by default it's `false`) w/o CUPS even present on the system. So your results are pretty much expected.

What about PSCRIPT.DRV options such as duplex etc, I see some code that attaches the IBMNULL driver to the PS printer before sending data to its spooler. The code says that this to strip all printer-specific feature settings added by PSCRIPT.DRV from PS data because if such data is sent to CUPS, CUPS will freak out. However, IBMNULL is forced only if `print.os2.postscript.use_ibmnull` is set to `true` (which is the default). So, if it's `false`, all printer specific settings like DUPLEX etc should finally reach the printer w/o problems since the native PSCRIPT.DRV should be used in such a case. @dspiatkowski can it be that you have `print.os2.postscript.use_ibmnull` set to `false`?

Anyway, I'm closing this in favor of #171 where we decide what to do with native printer support. We will align README.OS2 accordingly within that issue.

**Comment by dspiatkowski** [comment]
Hi Dimitriy!

On Thu, 14 Sep 2017 20:05:57 +0000 (UTC), Dmitriy Kuminov wrote:

> ...
>What about PSCRIPT.DRV options such as duplex etc, I see some code that attaches the 
IBMNULL driver to the PS printer before sending data to its spooler. The code says that this to 
strip all printer-specific feature settings added by PSCRIPT.DRV from PS data because if such 
data is sent to CUPS, CUPS will freak out. However, IBMNULL is forced only if 
`print.os2.postscript.use_ibmnull` is set to `true` (which is the default). So, if it's `false`, all 
printer specific settings like DUPLEX etc should finally reach the printer w/o problems since the 
native PSCRIPT.DRV should be used in such a case. @dspiatkowski can it be that you have 
`print.os2.postscript.use_ibmnull` set to `false`?
> ...

YES!!! Thank you, that is precisely the case. I had not touched the default setting of 
`print.os2.postscript.use_ibmnull` having left it at TRUE. However, per your explanation above, 
changing to FALSE allows the `print.os2.postscript.use_builtin` to fully respect all Postscript 
driver settings. Tested here by printing some duplex pages, no problem, output is formatted 
correctly as per the Postscript print job definitions.

Thanks,
-Dariusz
