### ISSUE TITLE
FF45.5 release - delayed response/choppy window scrolling...

### ISSUE THREAD

**Issue by dspiatkowski** [bitwiseworks/mozilla-os2#208]
Installed the 45.5 release of FF having installed the various pre-reqs...it came up OK, but very quickly found out that pretty much all feedback to any input (window scrolling, text typing - such as in this window) is very choppy and delayed!

This means, there is a pronounced delay in the browser response.

To better describe this is to say that if one were to turn off the "Smooth Scrolling" feature the results would be what I'm seeing.

I disabled the SET NSPR_OS2_NO_HIRES_TIMER=1 mode next, just to rule it out...behaviour is still the same.

BTW: this is on a 5 core SMP box...plenty of CPU power, but strangely the CPU monitor shows very little activity.

**Comment by dryeo** [comment]
I find the same thing with SeaMonkey as well as when switching tabs, 
there is initially a lot of black in the initial drawing before about 
half a second when the tab is drawn correctly. Seems to be a gecko issue.

**Comment by dspiatkowski** [comment]
Hi Dave,

On Sat, 20 May 2017 20:16:20 -0700, Dave Yeo wrote:

>I find the same thing with SeaMonkey as well as when switching tabs, 
>there is initially a lot of black in the initial drawing before about 
>half a second when the tab is drawn correctly. Seems to be a gecko issue.
>
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/bitwiseworks/mozilla-os2/issues/208#issuecomment-302912273

The one comment I would add to this is that even once the page is completely
rendered any input, such as scrolling the page, or filling out an INPUT text
field is very slow...

Thanks,
-Dariusz

**Comment by wztest** [comment]
Same here, page is 100% loaded and then when using the scroll bar there's a delay to really move the page and the scroll bar itself and in first place it looks like the browser is not accepting any input (like with high CPU usage) but there nearly no CPU usage in this moment.
Is there an addition debug option to check what's going on in the background?

**Comment by dspiatkowski** [comment]
On Sun, 21 May 2017 01:40:33 -0700, wztest wrote:

>Same here, page is 100% loaded and then when using the scroll bar there's a delay to really move the page and the scroll bar itself and in first place it looks like the browser is not accepting any input (like with high CPU usage) but there nearly no CPU usage in this moment.
>Is there an addition debug option to check what's going on in the background?

Yes, you need to d/l the symbol files (see =>
https://github.com/bitwiseworks/mozilla-os2/releases/download/FIREFOX_45_5_0esr_
RELEASE_OS2_Beta_8/firefox-dbgsym-45.5.0.en-US.os2.zip), but I am going to
hold-off on installing these until dimitriy has a chance to look at this, there
may be other things he might need...

Also, make sure you have the latest versin of EXCEPTQ installed (see =>
http://home.earthlink.net/%7Esteve53/betas/exceptq-7.11.4-shl-2017-03-06.zip).

**Comment by dryeo** [comment]
On 05/21/17 01:40 AM, wztest wrote:
> Is there an addition debug option to check what's going on in the
> background?

Look under tools-->Web Developer. My nightly has quite a few tools 
available.

**Comment by wztest** [comment]
@dryeo which nightly and where? Debug symbols will only help when Firefox will crash but slow rendering doesn't crash the browser here.

**Comment by dryeo** [comment]
On 05/22/17 11:44 AM, wztest wrote:
> @dryeo <https://github.com/dryeo> which nightly and where? Debug symbols
> will only help when Firefox will crash but slow rendering doesn't crash
> the browser here.

The version of FF that I built here. I haven't the bandwidth to download 
the official one, so don't know if the menu's are the same.

**Comment by dspiatkowski** [comment]
Hi Silvan,
I noticed that you tagged this ticket/issue as "enhancement" as well as "bug" & "task"...I think it should be considered "bug" only given that the application was responsive, as always in the past in all prior releases. Please let me know if I am incorrectly interpretting what the tags mean.
Thanks,
-Dariusz

**Comment by SilvanScherrer** [comment]
As soon as we know it's a bug only we will tag it like that. But it might well be we have to enhance the port as well. That's why a task to enhance the bug :)

**Comment by dspiatkowski** [comment]
Hi Silvan,

On Tue, 23 May 2017 23:44:17 -0700, Silvan Scherrer wrote:

>As soon as we know it's a bug only we will tag it like that. But it might well be we have to enhance the port as well. That's why a task to enhance the bug :)

Alright...thank you!

What a very clear explanation...no reason for me to guess here, just a
straight-up content made up of process details...I love it.

**Comment by dryeo** [comment]
Another symptom is that right clicking to display a context menu often 
displays the last context menu and is slow to paint, eg part of the 
context menu is painted black.
Test by right click on text, a URL and an image in different orders.

**Comment by lerdmann** [comment]
Unfortunately, on my system, FF 45.5 is close to being unusable. That's really unfortunate as the printing now works where in FF38.8.0 it did not.

I tried this:
1) marking the DLLs that are in the FF directory (3 DLLs) to load the code segments in high memory
2) copying "plugin-container.exe" and "updater.exe" from an older installation to the new FF directory just to see if the lack of "plugin-container.exe" leads to some odd effects (I know it is not used but maybe firefox.exe is looking for it ...)

None of that made a difference. By the way: if it blocks, it is not the firefox.exe process that hangs but rather pmshell.exe (the 2. instance) that's cycles at 100 %. I am not clear about the interaction between these 2 processes but maybe this is related to some drag and drop (support functionality) issue ?

Lars

**Comment by wztest** [comment]
@lerdmann its unusable because of the 'scroll/refresh' issue? plugin-container.exe is maybe out of the game as with the new releases it itself caused 100% CPU load. In case RWS is installed you can try to disable it with MOZ_NO_RWS=1

**Comment by DavidMcKenna** [comment]
I don't get hangs, but videos are unwatchable on version 45 (like watching stop action animation) even though sound is fine. Tried changing various setting but no help. Finally gave up and went back to 38...

**Comment by dmik** [comment]
I confirm general slowness of ESR 45. I have a feeling that it's somehow related to timer message processing and/or interval handling. Looks like short timers actually take much longer time to complete or something like that. Painting operations itself are super fast (as fast as before), it's just intervals between paint events that are now long for some reason. This needs investigation.

**Comment by dmik** [comment]
Trying the debug build of Mozilla indicated that we lack the VSync support:
```
[3359] WARNING: Hardware Vsync support not yet implemented. Falling back to software timers: file D:/Coding/mozilla/master/gfx/thebes/gfxPlatform.cpp, line 2120
```
I immediately thought that this is the reason of the slowness as it matches my feeling about some delays between paint events. And I must say I was completely right.

In around FF38 or so they started implementing what's called [Project Silk](https://wiki.mozilla.org/Project_Silk). Basically, it's a hardware VSync timer implementation used by the compositor and the painter to make visual performance of the browser more smooth. There is also an interesting post from the developer here: https://hacks.mozilla.org/2015/01/project-silk/.

In ESR 38, if I read the code right, hardware Vsync was disabled by default and the compositor worked in so-called ASAP mode when it composes frames as soon as possible w/o any bounding to frame rate. In FF 39 and up hardware Vsync is on and on platforms lacking its native implementation (OS/2 included) software emulation of Vsync timers is used. This software emulation uses a dedicated thread with a chomium-flavor message queue that posts events to itself at a given frame rate interval (60 frames per second by default) and these notifications are then sent to the compositor.

Given that software timers in general (and on OS/2 in particular) are far from being accurate (needless to say uniform), this gives quite poor performance, once Vsync is enabled. On OS/2 it's so inaccurate that frames are being painted with big delays, not even roughly close to 60 FPS. Hence the overall jank in performance. On OS/2 chromium timers use POSIX `clock()` (which uses the MS counter from the global info segment) to measure intervals and WM_TIMER messages to sleep for a specified amount of time. All this has quite a low resolution so no surprise it behaves poorly. While I could fix chromium to use the OS/2 high-resolution timer it makes little sense as WM_TIMER still uses low res timers (I believe). And there is no reliable way to use custom timers if you need PM message queue integration.

So, unless someone has an idea on where to take hardware Vsync events on OS/2 from, we will have to live with ASAP mode. This mode may be easily enabled even now with setting `layout.frame_rate` to `0` in `about:config` (the default value is `-1` which means use hardware Vsync when available and fall back to software otherwise). Any other positive value is the desired frame rate for the software Vsync emulation. The default value of 60 FPS (eventually used on OS/2 when `layout.frame_rate` is `-1`) is obviously not enough for us. I start getting good results with 1200 FPS and higher but better set it to zero as this provides some more optimizations for the ASAP mode.

**Comment by dmik** [comment]
So everyone, please test ESR 45 with `layout.frame_rate` set to `0`. Here it behaves just like ESR 38 did. I will make this value a default on OS/2 for the time being.

**Comment by dspiatkowski** [comment]
Hi Dmitriy!

On Thu, 15 Jun 2017 12:31:07 -0700, Dmitriy Kuminov wrote:

>So everyone, please test ESR 45 with `layout.frame_rate` set to `0`. Here it behaves just like 
>ESR 38 did. I will make this value a default on OS/2 for the time being.

I read your in-depth analysis of this issue with great interest. Does the hardware 
implementation of Vsync then require something like an OS/2 specific device driver? I'm sorry, I 
know very little about the FF source and technology, but given the FF Silk project article you 
kindly highlighted it seems this unfortunately is not just a matter of further porting of some 
other library. It appears that other platforms have the ability to intercept (or issue) an API call 
to the video device driver to obtain visibility to the screen refresh sync. For us that would imply 
developing something similar in Panorama, SNAP or heck, even the default GRADD???

In SNAP specificaly (because that is what I'm currently using and have played around with the 
SDK in the past) the Vsync timing details I think are available in the GA_CRTCInfo structure. 

Still, the question remains: how does one consistently interface to this? An API call like IsVSync 
(Determines if the card is currently within the vertical retrace interval), or perhaps WaitVSync 
(Waits until the graphics card enters the vertical retrace interval) could be used perhaps? I 
have no experience with these, but the info above came directly from the SDK docs and if the 
description and functionality of something like WaitVSync is correct, that could be used as the 
trigger to kick of the start of each frame build?

Anyways, for now, I'm happy to test out the recommended by-pass solution. Will you be 
releasing the 45.9.x for this, or should I go back to 45.5.x?

Ahh, also, I found the Vsync testing site (http://www.vsynctester.com/) listed in that article to 
be a good visual indicator of how the various parameters impact results...for those of us intent 
on playing with the 'layout.frame_rate' setting this may give some pretty direct visibility.

Thanks,
-Dariusz

**Comment by SilvanScherrer** [comment]
With this setting is behaves like it did in the 38 times. As there is a VSync issue #220 which deals in detail with the possible enhancement, we might close this one now.

**Comment by dmik** [comment]
@dspiatkowski you get it right, we need something like WaitForVSync that does not return until a Vsync cycle is about to start. And we need help from the video driver here, no doubt. But please let's continue within #220 if you are interested. Closing this.
