### ISSUE TITLE
H264 and AAC broken?

### ISSUE THREAD

**Issue by dryeo** [bitwiseworks/mozilla-os2#216]
http://html5test.com/ reports that our browser (Firefox 45.5.0 and SM 2.42) no longer support H264 and AAC. These worked with the 38ESR branch as long as the FFmpeg libs were on the LIBPATH. Unluckily I don't have the bandwidth to do much more testing

**Comment by dmik** [comment]
It's broken indeed, looks like they changed the code that loads FFmpeg DLLs, a hundredth time. Need to check this.

**Comment by dmik** [comment]
The new code attempts to load `libEGL.so`, this is clearly wrong but I remember I did something related to that when merging ESR 45 changes in. Needs to be checked.

Also I see now that the old code loading FFmpeg DLLs on the fly was moved from `dom/media/fmp4/ffmpeg` to `dom/media/platforms/ffmpeg`. Since our OS/2 patches were never there, they got lost. Need to restore it.

**Comment by dmik** [comment]
Loading libEGL is disabled in 196b49ca4917b823b46035f5923c55fd5972338b as it makes no sense ATM (there is no EGL port for OS/2 yet).

Loading FFmpeg is restored (see the above commit). Note that together with H264/AAC this also brought MP3 support according to html5test.com. Though I can't test it in real life since I have a problem with UNIAUD on my new OS/2 machine (it loads but no sound).

**Comment by dryeo** [comment]
MP3 playback works here, at least with a local file. Volume and mute is 
broken though, covered in issue #190.
