### ISSUE TITLE
HTML5 , no game sound

### ISSUE THREAD

**Issue by Barndras** [bitwiseworks/mozilla-os2#222]
Tested older FF and the latest beta, no gamesound

http://rpg.mo.ee/ , its html5 and mp3.

There is another link the devs from MarxGames gave me with ogg sound same issue:.http://rpg.mo.ee/index.html?inapp=desura.

Tried other html5 games , same problem.

**Comment by dryeo** [comment]
Are you sure your volume is turned up? Try installing 
http://hobbes.nmsu.edu/download/pub/incoming/PMUniMix-bin-0_82.zip and 
turn up all the volume controls. Here I have to turn up the front 
speakers to hear any sound.

**Comment by dmik** [comment]
In our latest FF 45.9.0 test drop, we enabled playing MP3 via FFMPEG libs. And OGG has been working since ages (since FF 24 IIRC) w/o any external dependencies. So if OGG doesn't work for you in FF then you have an issue with your sound card or with your mixer settings (please try what @dryeo suggests).

There is an excellent test for supported audio formats: https://hpr.dogphilosophy.net/test/. FF 45.9.0 supports all of the formats on that page except FLAC. Does anything work for you there?

**Comment by Barndras** [comment]
Thanks all, i tested latest http://rpm.netlabs.org/test/yb9p2.zip and installed ffmpeg libs and it worked :-)
Performance is bad but well its a new FF buil: https://youtu.be/jM06Ol1AlOY

**Comment by SilvanScherrer** [comment]
As the issue reported (no sound), is fixed I close it.
Feel free to open a new issue, if you find some other bugs.
