### ISSUE TITLE
Awget binary NP plugin doesn't work

### ISSUE THREAD

**Issue by dryeo** [bitwiseworks/mozilla-os2#225]
Awget, http://glass.ptv.ru/awget.html ,comes with some plugins, of which I have npawgbin.dll installed. In previous versions,up to FF 38ESR clicking on a zip file at Hobbes would invoke the awget popup and then pass control to wget (or curl depending configuration) much the same if you configure it to monitor the clipboard.
With the official Firefox 45.5 and newer personal builds, it simply fails, giving a blank screen and if plugin-container.exe is present, 100% CPU. With SeaMonkey, similar except if plugin-container.exe is present it often generates this weird incomplete trp, while crashing, leaving plugin-container.exe running in the background using 100% of one core.
```

______________________________________________________________________

 Exception Report - created 2017/06/23 19:55:33
______________________________________________________________________

 OS2/eCS Version:  2.45
 # of Processors:  2
 Physical Memory:  3581 mb
 Virt Addr Limit:  3072 mb
 Exceptq Version:  7.11.3-shl (Jul  5 2016)

______________________________________________________________________

 Exception C000009F - Breakpoint
______________________________________________________________________

 Process:  C:\USR\LOCAL\LIB\SEAMONKEY-2.42.9ESR\SEAMONKEY.EXE (06/20/2017 03:21:27 88,114)
 PID:      7C (124)
 TID:      01 (1)
 Priority: 200

 Filename: K:\USR\LIB\NSPR4.DLL (05/02/2017 07:33:09 309,942)
 Address:  005B:1E026C10 (0001:00006C10)
```
SeaMonkey has many tabs open and an old profile while Firefox has a fairly new profile and one or two tabs open.

**Comment by dmik** [comment]
Using the plugin does not crash here but it doesn't work either, I see this in the child process:
```
[NPAPI 15364] ###!!! ABORT: Aborting on channel error.: file ~/Network/novator_D/Coding/mozilla/master/ipc/glue/MessageChannel.cpp, line 1861
[NPAPI 15364] ###!!! ABORT: Aborting on channel error.: file ~/Network/novator_D/Coding/mozilla/master/ipc/glue/MessageChannel.cpp, line 1861
```
Something's still not working right (se #106 for more info about IPC issues). I need to do more logging.

**Comment by dmik** [comment]
Note that there is also this message preceding the above one:
```
###!!! [Parent][MessageChannel::Call] Error: Channel timeout: cannot send/recv
```
Deep analysis shows that this happens because the child process started to execute the plugin never returns from a call to `NP_Initialize` in the actual plugin DLL and gets killed by the parent (the main FF process) after a timeout (30s or so). My guess is that the plugin DLL (NPAWGBIN.DLL in this case) tries to call some NPN browser function via a table of functions it gets as the first argument of `NP_Initialize` but this function never returns. I need to do more analysis to see why it happens.

Sad that the debug build of FF crashes here (some dirty JS crash) so that I can't enable extra logging for IPC (available only in the debug build) and have to manually insert a lot of `printf` in many files to see what's going on. OTOH, I get much better understanding this way. But it's kinda slow.

**Comment by dmik** [comment]
I guess I know why it hangs. The first thing the AWget plugin does is creation of a popup window with the clicked URL. In FF 38 and earlier it was done on thread 1 in the same process where the browser runs so it just worked. Now the plugin is loaded in another process. And while this process is morphed to PM and has a message queue, it doesn't actually run this message queue because IPC uses `libevent` which in turn uses select and sockets on OS/2. So my guess is that it hangs because no PM message queue is being run. This also may be a reason why the Flash plugin fails in `CreateChildPluginWindow`.

At worst, I will have to fusion both select and the PM message queue as I already did multiple times for Qt back then.

**Comment by dmik** [comment]
Discard the last comment; I already implemented this fusion in chromium back in 2013, see e.g. d5528e6e. So there must be something else. Too bad that we don't have NPAWGBIN.DLL sources.

**Comment by dmik** [comment]
I have to give up with this for now because I have no more ideas why it hangs. I need the plugin DLL source to tell more. And no way to have it working in in-process mode since there is no in-process mode for plugins since ESR 45 any more.

Note also that the Flash plugin issue is completely different, `NP_Initialize` works great for it (i.e. the child process successfully handles it and returns to the parent). It doesn't fully work still but that's off-topic here (it belongs to #43).

**Comment by an64** [comment]
Its me again with my 5 cents
npdjvu have a sources , see #47 
maybe it helps

**Comment by dmik** [comment]
@an64 NPDJVU is also a problem. `NP_Initialize` works there but it gets stuck in `NPP_SetWindow`, symptoms are the same as with NPAWGBIN: no response in 30s and a subsequent kill. Also, Firefox warns me that the plugin is vulnerable and should be updated.

But I already got NPAWGBIN sources so it's much easier for me to continue with it (it's a much simpler code than NPDJVU).

**Comment by dmik** [comment]
Ok, investigating the sources revealed the following:

1. The environment of the child process is clean, meaning that e.g. ETC is set to nothing instead of `C:\MPTN\ETC`. This way, AWget can't load its config file and:
2. It tries to call `WinMessageBox` with an error message and this is where the process hangs.

So for some reason the window can't be displayed and makes this process hang until killed. May be it's empty environment, may be it's something else (note that this thread *does* run the PM message queue so it's not an issue per se). I will tell more after a short break.

**Comment by dmik** [comment]
I fixed the environment in the child process but it doesn't help with `WinMessageBox`. I noticed though that when the child process gets killed, the message box appears for a second or so. Really strange. I'm missing something here. It should just work.

**Comment by dmik** [comment]
Even more strange that when I start `plugin-container.exe` directly, `WinMessageBox` works.

**Comment by dmik** [comment]
Starting `plugin-container.exe` from my test PM application also works fine. Both when this test app is started by DosExecPgm (e.g. from `sh.exe`) or by DosStartSession (from `cmd.exe`). It even works if compiled as a VIO app initially, due to morphing from VIO to PM that I always do there.

However, starting a native PM app (e.g. `e.exe`) from this test PM app only works if this test PM app itself is started by DosStartSession (i.e. via `cmd.exe`). If you attempt to start it by DosExecPgm (i.e. from `sh.exe`) the test app itself works, but the `e.exe` window does never show up. But this is perhaps because `e.exe` doesn't know how to morph from VIO to PM at runtime. Running `e.exe` from `sh.exe` also doesn't work which proves this.

All in all, the FF and `plugin-container.exe` looks like some sort of SMQ (single message queue) issue but I can't figure what triggers it yet.

**Comment by dmik** [comment]
Note that my hello PM app has basically the same startup code as Firefox. This means that Firefox does something during its runtime that causes this screwup. I need to find what.

**Comment by dmik** [comment]
All factors and my further tests indicate that we have a problem because the parent process doesn't run the PM message queue while waiting for the child startup confirmation. This would explain it all (unresponsive Firefox window, not showing the child window, and impossibility to use any other PM app while FF is waiting) given that we actually have SMQ  (single message queue) on OS/2. I need to dig further in order to see why the message queue is not run. I'm pretty sure that it will fix the problem.

BTW, I found a nice place where we can disable running plugins in child processes once and for all: it's `nsNPAPIPlugin::RunPluginOOP(const nsPluginTag *aPluginTag)`. Currently it simply returns `true` for all platforms but Android (it used to contain some logic to enable/disable OOP for plugins depending on `dom.ipc.plugins.enabled.*` which was completely removed by the ESR 45 update). Making it return `false` disables OOP for all plugins and effectively makes NPAWGBIN.DLL and even Flash (NPFLOS2.DLL) work. We will use it as a fallback if I fail to fix the remaining problem with PM messages within reasonable time (1-2 more days).

**Comment by StevenLevine** [comment]
I'm late to the party.  A couple of comments, some of which you appear to have already discovered.  DosExecPgm is limited to starting apps of the same type.  I'm pretty sure that the app type is the type defined in the module header and not the result of morphing the parent app.  IBM never supported morphing, even though it continues to work.  The solution is to use DosStartSession.  I would expect DosExecPgm to fail from sh.exe because sh.exe is VIO app.

**Comment by StevenLevine** [comment]
By fail I mean that the PM all will not run correctly.  DosExecPgm returns without error.

**Comment by dmik** [comment]
@StevenLevine yes, I know that DosExecPgm may only start a process in the same session as the parent. This isn't a problem for apps that know how to morph — they will be able to run PM no matter which session type the parent has. However, if they don't morph, they will fail to use PM indeed. This means that morphing (changing  `pib_ultype` of PPIB to 3) is not considered by OS/2 as changing the session type actually: children will start in a session that the process had before morphing. Most likely, the session type is defined solely by the EXE header. At least CMD.EXE behaves just like that: it will use DosExePgm for apps marked as VIO in the header and DosStartSession for ones marked as PM (even if it's a trick — just try to mark any VIO EXE as PM and you will see).

As for `sh.exe`, we should fix starting PM apps there (like e.exe or newview.exe) which is completely broken now. However, the guilty party here is kLIBC whose `exec/spawn/fork`: a) can't detect the app type from the EXE and b) can't do P_SESSION/P_PM starts at all. There is a respective kLIBC ticket: http://trac.netlabs.org/libc/ticket/121. Once kLIBC is fixed, `sh.exe` and all other apps using `exec/spawn/fork` will just work. But that's surely an off-topic for this issue.

**Comment by dmik** [comment]
Ok, it's clear more or less. And I was right. On OS/2 `GeckoChildProcessHost::WaitUntilConnected` eventually uses `PR_WaitCondVar` which in turn uses `DosWaitEventSem` on GUI thread to wait until the child process gets connected and notifies the parent through a socket (with `select` running on a secondary thread). `DosWaitEventSem` doesn't run the PM message queue and that's the reason why the parent (the main FF process) gets stuck. However, due to SMQ, calling such a blocking waiter on the main PM thread of one app effectively blocks the whole PM completely and that's why the started can't even show a simple message box.

I still wonder how it's done on Windows as there NSPR uses `WaitForSingleObject` which blocks the GUI message queue as well IIRC. There is, however, a set of hacks in `WindowsMessageLoop.cpp` (and `mozilla::ipc::windows::InitUIThread()` in particular) that, according to the comments exists to solve the problem of deadlocks when sending synchronous IPC messages to processes that contain native windows so I guess these hacks somehow solve this problem on Win. What they do there is install some window create/destroy hooks and run some mini message loop during some interrupts. I'm not sure if this is possible under PM. Most likely I will have to modify the wait loop so that it uses a PM message loop underneath.

**Comment by dmik** [comment]
I recall that there is actually `WinWaitEventSem` which we may use instead of `DosWaitEventSem` on OS/2 (similarly to `MsgWaitForMultipleObjects` on Windows). I will play with it but I have to hack NSPR again (BTW< there are already two pending FF-relatedc hacks, see the NSPR timeline).

**Comment by dmik** [comment]
I must confirm that using `WinWaitEventSem` instead of `DosWaitEventSem` in NSPR completely fixes the problem with the NPAWGBIN.DLL plugin in OOP mode — clicked files are properly sent to the AWget daemon for downloading. This means that IPC communication generally works on OS/2 now.

We have to decide how to better change NSPR as just using `WinWaitEventSem` creates a static dependency on `PMWIN.DLL` which will make NSPR unusable in PM-less environments which is not right as there are some text mode apps using it. But this is off-topic here, I created http://trac.netlabs.org/ports/ticket/166 for that.

I will leave this open until NSPR is done and #106 is closed.

**Comment by dmik** [comment]
NSPR is actually already done (see the ticket) and it appears that the plugin fully works now after the above commit. Closing.
