### ISSUE TITLE
Printing of PDF with internal PDF viewer

### ISSUE THREAD

**Issue by SilvanScherrer** [bitwiseworks/mozilla-os2#231]
When Firefox shows a PDF with the internal viewer, you have the possibility to print it as well. If I hit the printer symbol at the upper right location (within the PDF view), all I get is a message box with "An error occurred while printing".

**Comment by dryeo** [comment]
That's actually a print preview button, even though labeled print. I 
guess if print preview still worked, you would print from the print 
preview window. Both using the File-->Print Preview and the PDF Print 
widget have the same result, the print preview window is partially drawn 
and then the "An error occurred while printing" popup titled "Print 
Preview" dialog shows.
I'd suggest changing this issue to "Print Preview is broken" as printing 
a PDF to file with the File-->Print menu item does work.

Tested with Firefox and SeaMonkey using the IBM NULL and an Apple 
Laserwriter drivers.

**Comment by SilvanScherrer** [comment]
I'm not sure if that's really the case. As File -> Print Preview works here (also for PDF). At least the Preview is shown. But as said when I hit the Print button in the internal PDF viewer all I get is the error message.

**Comment by dmik** [comment]
Here it's exactly like Dave says: attempting to do File -> Print Preview gives an "error occurred" message box, no matter which web page I'm on. Silvan, can it be that you somehow have a custom print setup in your Firefox profile? Could you try a clean one?

**Comment by dmik** [comment]
Some notes. I was always getting the error because I had no configured printers at all. Once I installed a fake PSCRIPT.DRV printer and set `print.os2.postscript.use_builtin` to `true`, I can always generate a preview via File -> Print Preview but pressing a Preview button in the built-in PDF viewer immediately fails indeed. This needs an investigation.

**Comment by dmik** [comment]
I found something. An attempt to open a XUL window with printer settings causes 0x80570027 which is NS_ERROR_XPC_SECURITY_MANAGER_VETO. So the security manager somehow prevents it from being opened. And on Windows they use a native print dialog which doesn't go through the security check, so it works. I need to dig into this security stuff (and look around).

**Comment by dmik** [comment]
This is really-really-really-over-complex. Since it's basically a web page that wants to open a print dialog, this involves IPC, JS and security checks. It fails when attempting to set a JS property containing the print settings object in the outer JS context. This code:
```
  nsIScriptContext *ctx = GetOuterWindowInternal()->mContext;
  NS_ENSURE_TRUE(aArguments && ctx, NS_ERROR_NOT_INITIALIZED);
  AutoJSContext cx;

  JS::Rooted<JSObject*> obj(cx, GetWrapperPreserveColor());
  return ctx->SetProperty(obj, "arguments", aArguments);
```
returns NS_ERROR_XPC_SECURITY_MANAGER_VETO when setting the `arguments` property. I have to figure out why. Most likely something's missing in our IPC implementation. And this may affect other IPC cases of course.

**Comment by dryeo** [comment]
Which window do you mean, the page setup window? They all seem to open 
fine on TB and SM, though the printer properties is an OS/2 native 
window, "Postscript Job Properties - Generic Postscript Printer Version 
30.822"
I don't actually have a printer.

**Comment by dmik** [comment]
No, I mean the Firefox-driven Print dialog that opens when you select File -> Print. JS is sandboxed since long (so that it can't get access the real OS behind FF) and there is a security manager that defines what is allowed for the script to do. Somehow a call to open a top-level window from the Firefox-own PDF viewer script gets blocked by it on OS/2. Either we don't white-list it properly or lack something in IPC again.

**Comment by dmik** [comment]
Going further. Found that it's `nsScriptSecurityManager::CanCreateWrapper` that returns NS_ERROR_DOM_XPCONNECT_ACCESS_DENIED for an `nsIPrintSettings` instance that `nsPrintingPromptService` tries to pass as the `arguments` array element to the JS context of the new top-level window (which is intended to contain the print settings dialog).

This `nsScriptSecurityManager` only allows to pass those instances that are of DOM classes or those that are white-listed. Also, any instance is allowed if the caller is Chrome. All other instances are rejected. Apparently, on OS/2 all of these three conditions fail for some reason (which I need to find out), while on other platforms one of these conditions is met.

**Comment by dmik** [comment]
BTW, this is a Mozilla bug somehow related to this: https://bug98304.bugzilla.mozilla.org/show_bug.cgi?id=932906.

**Comment by dmik** [comment]
BTW, the error reported by `nsScriptSecurityManager::CanCreateWrapper` is
{{{
Permission denied for <resource://pdf.js> to create wrapper for object of class UnnamedClass
}}}
Given that `nsPrintSettings` implementing `nsIPrintSettings` doesn't implement `nsIClassInfo` (hence `UnnamedClass`), it can never identify itself as a DOM class. This leaves us with two choices: either it's a remote-XUL domain that should be white-listed and it's not or the caller is Chrome but it isn't identified as such.

I guess it's time to build Mozilla for Mac to see what's going on there, it may be faster than digging further.

**Comment by dmik** [comment]
Mozilla for Mac is built and runs (btw, it takes basically the same 2h to build like on OS/2 on a quad core i7). However, I found that they use a completely different code path so unfortunately this didn't work out. I need a windows build...

**Comment by dmik** [comment]
My current bet is that its `IsCallerChrome` that returns false on OS/2 while it should return true. But I can't track down the logic of all this machinery so far, it's way too complex. May be the reason is that it's supposed that this code runs in OOP and OOP is completely disabled on OS/2 ATM (while it's the default way to go on all other platforms now). And running it in-process somehow breaks IsChrome detection.

**Comment by dmik** [comment]
Of course, I can hack the check to let it pass when origin is `resource://pdf.js` and this is safe as it's always an internal script (I checked and it works well of course). It's a last resort option but we should fix the root of the problem anyway, now or later.

**Comment by dmik** [comment]
Okay, I did a lot of digging on the issue, checked FF on Mac/Win/Linux and even talked to the Moz devs on #content at irc.mozilla.org ([here](http://logs.glob.uno/?c=mozilla%23content&s=25+Sep+2017&e=26+Sep+2017&b=1) is the transcript) to confirm some thoughts. Here is the essence. On all platforms but OS/2 `nsPrintingPromptService::ShowPrintDialog` uses a native print dialog which replaces the old, XUL-based, which is still present in the upstream code base and gets used as a fallback (and so it does on OS/2 as we lack native print dialog support). However, this XUL-based dialog (initiated by `nsPrintingPromptService::DoDialog`) broke after Mozilla introduced strict security checks for JS code via `nsScriptSecurityManger::CanCreateWrapper` (long time ago, between FF24 and FF31 IIRC). But given that this fallback dialog isn't used any more on Tier 1 platforms, this break has been unnoticed until now. The sad news that it's not going to be fixed upstream any time in the near future (because it doesn't affect Tier 1 platforms) and it's obviously too expensive to properly fix it ourselves because this may require some major design decisions regarding JS security.

So I will go a much simpler way, as mentioned in the previous commit.
