### ISSUE TITLE
Support OS/2 trace in XUL.DLL

### ISSUE THREAD

**Issue by dmik** [bitwiseworks/mozilla-os2#259]
This ticket is to add support for the OS/2 trace facility to XUL.DLL and other Firefox EXEs and DLLs. The target is to get a full stack trace of what's being called during the Firefox session for analysis — both functional and performance-wise.

The primary goal is to crack the #248 problem but it will surely be useful for general development as well.

**Comment by dmik** [comment]
There are basically two ways of achieving this:
- use DTRACE BUILDTDF on a special file describing tracepoints (see OS2TRACE.INF)
- use TRCUST on a TSF file generated from the map file (see TOOLSREF.INF)

Both approaches generate a binary TDF file that is used by the OS/2 trace facility to log trace events to the trace buffer (these files are stored in \OS2\SYSTEM\TRACE). The first approach seems very flexible as it allows to write subprograms using a special language in RPN notation that will be executed at trace points. The second approach makes heavy use of the debug info generated by the compiler (like symbol and variable names and so on) so things appear a bit easier there. However, TRCUST is really an old (16-bit?) program that has many bugs. I.e. it cannot parse HLL debug info generated by EMX.

So when using the second approach only the name of the trace point (in most cases — function entry point) is easily available. The rest requires some non-trivial work. Note that the first approach requires even more work as even the opcodes of the trace point should be manually extracted from the DLL or executable, BUILDTDF isn't able to do it on its own (have no idea why). Also, BUILDTDF, as opposed to TRCUST does not generate TFF files. TFF files contain basic tracepoint properties (such as its name, e.g. the function name entry or exit). And only TRCUST (to my knowledge) may generate TFF files. Without TFF, one will have to manually format the raw trace buffer which is of course additional work (also non-trivial due to the lack of information etc.).

**Comment by dmik** [comment]
Okay, bad news. When I manage to generate a TDF/TFF file for XUL.DLL with *all* C++ symbols removed (which gives us around 3200 trace points), `trace on xul` produces a hard deadlock of the system where only a cold reset works. It managed to crash once but unfortunately I deleted POPUPLOG.OS2. But it was certainly C:\OS2\TRACE.EXE (I looked).

Given that it spitted a lot of `TRCUST(12700) ERROR: opcode at TP address cannot be traced` while generating the TDF file, I think that it would try to eat everything including data symbols in the code segment (yes, this is not unusual in GCC output: it often places const arrays in the code segment etc). And that could screw TRACE up while loading that TDF (a trace point at the variable is completely wrong of course). I need a higher level access to the symbols to check which is what (code or data) than the map file provides. Not easy to do, actually.

**Comment by dmik** [comment]
Although it's not always data. There is e.g. `NPN_pushpopupsenabledstate` which is quite a normal _Syscall function. However, TRCUST still doesn't like its opcode. Perhaps, its very limited in what it can understand. It seems that I will have to switch back to the BUILDTDF approach. However, no guarantee that a huge TDF built this way will also work.

**Comment by dmik** [comment]
BTW, the trace files causing OS/2 to hang are here: http://rpm.netlabs.org/test/xt.7z. Just copy them to \OS2\SYSTEM\TRACE and then execute `trace on xul` provided that the path to XUL.DLL is either the current directory or in BEGINLIBPATH. I wonder if you get anything else but a hard hang.

Note that these trace files contain just 3208 trace points — these are only raw C symbols from XUL.DLL, all C++ symbols (260 thousand!!) are removed because TRCUST failed to process some of these symbols complaining they are too long.

All in all, I start to really doubt that this approach will lead us anywhere. This facility was surely not meant for C++, it's mostly for drivers and simple and raw OS/2 native API calls.

**Comment by dryeo** [comment]
Did some experimenting with your trace files.
First with the RPM installed xul. Turning tracing on before starting 
Firefox resulted in a quick reboot upon starting FF. Turning tracing on 
after loading a high CPU page, 
https://www.patreon.com/posts/project-2ine-16513790 resulted in no 
crash, did trace off and used tracefmt to view the trace and save it. 
Closing Firefox hung the system.
Downloaded x3.7z hoping it was the newest and replaced xul.dll and 
repeated the test. First time the system rebooted about 10 seconds after 
doing the trace on xul. Next time I did trace off after about 5 seconds 
and tracefmt showed the trace, I saved it (938KBs vs the earlier 550KBs 
one), tried repeating but tracefmt complained the buffer was empty. Once 
again the system rebooted when closing Firefox.

The trace output seems to be things like,
```
(OS) Machine Exception 0e - Page Fault
Event [3]  Major [3/0x0003]  Minor [15/0x000f]  PID [82/0x0052]  CPU ID 
[0]  Length [20]  Time [15:17:19.16]
Error Code = 0000 0004 , CS:EIP = 0000005B 00014774 , EFlags = 0001 0246
Page Fault Linear Address (CR2) = 00014774
...
(OS) Hardware Interrupt Pre-Invocation
Event [66]  Major [4/0x0004]  Minor [9/0x0009]  PID [0/0x0000]  CPU ID 
[0]  Length [0]  Time [15:17:19.15]

Event [67]  Major [4/0x0004]  Minor [128/0x0080]  PID [1/0x0001]  CPU ID 
[0]  Length [0]  Time [15:17:19.15]
...
(OS) DevHlp_EOI Post-Invocation
Event [68]  Major [6/0x0006]  Minor [140/0x008c]  PID [0/0x0000]  CPU ID 
[0]  Length [2]  Time [15:17:19.15]
Return code=0000
...
(OS) Machine Exception 07 - Coprocessor Not Available
Event [3489]  Major [3/0x0003]  Minor [8/0x0008]  PID [80/0x0050]  CPU 
ID [0]  Length [16]  Time [15:17:17.73]
Error Code = 0000 0000 , CS:EIP = 0000005B 16C10C73 , EFlags = 0001 0212
...
OS2LVM Strategy-3 Request List Header Post-Invocation
Event [4909]  Major [7/0x0007]  Minor [202/0x00ca]  PID [0/0x0000]  CPU 
ID [0]  Length [8]  Time [15:17:17.65]
pRLH=F2DF3278  Status=04

(OS) DASD Manager Strategy-3 Request List Header Post-Invocation
Event [4910]  Major [7/0x0007]  Minor [154/0x009a]  PID [0/0x0000]  CPU 
ID [0]  Length [8]  Time [15:17:17.65]
pRLH=F9E21470  DoneCount=0001  Status=04

(OS) Trace Buffer Wrapped
Event [4911]  Major [0/0x0000]  Minor [3/0x0003]  PID [0/0x0000]  Length 
[0]  Time [. . . . . .]
```
None seem to be Firefox related, some are weird like the co-processor 
not being available.
I'm not an expert and can send them to you if you'd like
Dave

**Comment by lerdmann** [comment]
1) "TRCUST(12700) ERROR: opcode at TP address cannot be traced" rather looks like a failure to properly find the indicated code location of the dynamic tracepoint or to find a function prologue that trcust.exe does not expect. I think that trcust.exe tries to find/load the module (XUL.DLL), go to the code location (indicated by the symbol and the HLL debug info) and check if the opcode matches the expected one. If you do not specify the OPCODE= keyword, I would think that trcust.exe in lack of any better info, would look for a standard function prologue:
push ebp
mov  ebp,esp
If it does not find that at the indicated location (in particular, the first byte of the "push ebp" instruction), it will complain.
I had similar error message with using dtrace.exe and the RPN file approach and accidentally specifying the wrong opcode byte at the location that I was defining in the dynamic tracepoint.
The result will be that the TDF file is broken which would explain why the system will so heavily crash on activating trace points as likely the trace utility will patch in the INT3 at the wrong location, possibly right in the middle of an instruction ...
You can try other TDF files like CDFS.TDF and will likely run into the same problem as the TDF files seem to be older than the modules to be traced (CDFS.IFS in this case) and therefore don't properly line up.

Have you been using the TP=@filename,linenum approach or the TP=.name[+/-]offset approach ?
There is this cryptic info in the debugging handbook regarding the 2. approach:

> name
...  If debug information is used, the address of this tracepoint will be immediately following the prologue of the procedure ...

If your function does not have a standard function prologue, voila, that's where it can go wrong.

Also, the debugging handbook specifies that (for whatever reason) you cannot set a tracepoint on these instructions:
0x9C (pushf)
0xCC (int3)
0xCD (int n)
0xCE (into)
0x62 (bound)
0x69 (imul)
0x6b (imul)
0xf6 (div,idiv,mul,imul,neg,not,test with immediate operand)
0xf7 (div,idiv,mul,imul,neg,not,test with immediate operand)
but I think that the TRCUST warning message would be different from what you got.

2) Dave you have been running TRACE ON. That will enable ALL tracepoints, including the ones that are in various OS components. You'd rather need to do a TRACE OFF, followed by TRACE ON XUL (or so) to only select the tracepoints in XUL.DLL.

**Comment by dryeo** [comment]
On 03/06/18 11:01 PM, lerdmann wrote:
> #
>
> Dave you have been running TRACE ON. That will enable ALL tracepoints,
> including the one that are in various OS components. You'd rather need
> to do a TRACE OFF, followed by TRACE ON XUL (or so) to only select the
> tracepoints in XUL.DLL.
>

Hmm, I did do trace on xul in the Firefox directory. Perhaps it should 
have been in caps?

**Comment by lerdmann** [comment]
Dave, I think you forgot to specify TRACE OFF before specifying TRACE ON XUL.
If you run trace.exe /Q it will tell you which tracepoint major codes are active.

**Comment by dryeo** [comment]
OK, executing TRACE OFF and the TRACE ON XUL results in an instant OS lockup

**Comment by lerdmann** [comment]
Dimitry, I would suggest the following:
1) compile all the code in XUL.DLL with debug info, no optimzation and with standard stack frame. Also I think it would be necessary to not include code to do stack checking
2) write yourself a small utility that just loads XUL.DLL and polls/sleeps in an endless loop
3) apply your tracepoints against XUL.DLL
4) use Theseus to have a look at the XUL.DLL code and see where exactly the tracepoint(s) was/were applied. The byte will have changed to an INT3 (0xCC) instruction.

This way you can check if your expectations where exactly the tracepoint was set are met. It is possible that you will never be able to compile XUL.DLL with -O3 (or even -O2 or -O1 or -O) if you want to dynamically trace XUL.DLL as that might lead to entry code that does not have a standard stack frame.

Is there a gcc switch to force standard stack frames when optimization is on ?
I can see that if you specify -O, -O1, -O2, -O3 that that will activate -fomit-frame pointer which is exactly the problem here ...

**Comment by dmik** [comment]
Lars, thanks for your hints, though 1. is already the case (and has always been in my development env). I don't see how 2 and 3 can help. Anyway, it's just too much work, as there are way too many traces to handle them manually. Forcing standard stack frames is what I already thought about too. It's a way to go but I'm not sure if it will even compile & work as for this we will also have to disable inlining (heavily used with templates). Template usage in the Firefox code is very intensive nowadays. And even if it does compile, it might still give us nothing. I'll look into that direction.

Another option would be to split XUL.DLL back into several smaller DLLs as it used to be in the past. It would actually greatly simplify development and debugging by the cost of slowing down the overall compile time. However, it's slow as hell even now, so wouldn't make any significant difference on OS/2. Having multiple DLLs is better from all sides but making this split is a project of its own as the Firefox infrastructure is far away from this approach these days. I mean I'm not sure if making this split is faster than just finding this annoying a reason for this Gmail unresponsiveness. It might help us in the future too so I'll consider this split once again.

**Comment by dryeo** [comment]
There is the --enable-shared-js to split the JavaScript stuff off into 
its own DLL.

**Comment by lerdmann** [comment]
Ok. Dmitry can you tell me exactly what XUL.DLL matches the TDF file you are delivering with  http://rpm.netlabs.org/test/xt.7z ? I suspect that the TDF file does not align with the XUL.DLL you have applied the tracepoints to.
Have you created the TDF via the "dtrace BUILDTDF" command ?
Then I can do some research and hopefully can give you some advice in constructing a working TDF file. If you have a mapfile for XUL.DLL (along with the matching DLL) that is in the format mapsym.exe would understand that would even be more helpful.

**Comment by lerdmann** [comment]
I can see that you have built XUL.TDF with the "dtrace BUILDTDF" approach based on the MAP file you placed here:
http://rpm.netlabs.org/test/x3m.7z

but none of the XUL.DLL file dates for:
http://rpm.netlabs.org/test/x.7z
http://rpm.netlabs.org/test/x2.7z
http://rpm.netlabs.org/test/x3.7z

match that of the MAP file, where x2.7z comes closest in file date (MAP file and XUL.DLL are 2 days apart). Is it a good idea to investigate on  XUL.DLL contained in x2.7z ?

**Comment by dmik** [comment]
@lerdmann something's wrong on your side. The MAP file from x3m.7z exactly matches the DLL from x3.7z date wise. And the TDF file in xt.7z is built using this MAP file.

**Comment by dmik** [comment]
@dryeo yes, I remember that switch but we need much more than that. Even with JS excluded, XUL is extremely big nowadays.

**Comment by lerdmann** [comment]
I have a package ready where tracing on XUL actually works. Is there a place to upload ?
1) it works with http://rpm.netlabs.org/test/x3.7z. It is absolutely necessary to load this XUL.DLL. If necessary, the existing XUL.DLL needs to be backed up and replaced by this one
2) the package contains the tool that I used to create the XUL.RPN (for dtrace) and XUL.TSF (for trcust).
3) I had to manually comment out a couple of tracepoints in the XUL.PRN file. It became obvious that gcc.exe embeds data in the code segment !
4) firefox.exe will load and you can enable trace. It will eventually crash but won't bring down the whole system. I suspect that the "debug" XUL.DLL is just too big and I have not yet loaded it into upper memory
5) TRACEFMT.EXE just cannot format minor trace codes > 255. There is no way around it. That means minor codes > 255 will be shown unformatted.

**Comment by lerdmann** [comment]
As to 4.: yes, marking XUL.DLL code segment to load into high memory fixes the crash.

**Comment by lerdmann** [comment]
[package.zip](https://github.com/bitwiseworks/mozilla-os2/files/1798494/package.zip)

**Comment by lerdmann** [comment]
[package.zip](https://github.com/bitwiseworks/mozilla-os2/files/1798498/package.zip)

**Comment by lerdmann** [comment]
[package.zip](https://github.com/bitwiseworks/mozilla-os2/files/1798501/package.zip)

**Comment by dryeo** [comment]
On 03/09/18 01:23 PM, lerdmann wrote:
> As to 4.: yes, marking XUL.DLL code segment to load into high memory
> fixes the crash.

Here, I get
```
K:\usr\lib\firefox-45.9.0>trace on xul
SYS0487: The specified address is incorrect.

The TRACE utility cannot accept any of the trace definition
file(s) that were entered.  Trace status for the DLL libraries was not
updated.
```
After marking xul.dll to load code high. The trace does seem to work 
without loading the dll high until it crashes.

**Comment by lerdmann** [comment]
1) are you absolutely sure you are using the correct XUL.DLL ? You need to replace the one in the firefox-45.9.0 directory.
2) are you absolutely sure you placed the XUL.TDF into the very same directory and enabled tracing in that directory ?

But yes, tracing seems to be unreliable when XUL.DLL code is loaded high. I have to restart tracing every now and then to see some updates in tracefmt.exe. It does not crash though and I can properly use Firefox.

Another one: maybe you need to set VIRTUALADDRESSLIMIT to a higher value in order to be able to load XUL.DLL into high memory. I have it set to 3072.

**Comment by dryeo** [comment]
On 03/09/18 03:45 PM, lerdmann wrote:
>  1. are you absolutely sure you are using the correct XUL.DLL ? You need
>     to replace the one in the firefox-45.9.0 directory.

1-31-18  2:19a   455,007,754    124 a---  xul.dll

>  2. are you absolutely sure you placed the XUL.TDF into the very same
>     directory and enabled tracing in that directory ?

I do now (previously had it in os2\system\trace), same results. Works 
fine besides crashing after a bit without marking code high, won't trace 
with it loaded high.
The trace does refer to things like xul__text Entry and lots of xul 
_NS_CycleCollectorSuspect3 Entry

**Comment by StevenLevine** [comment]
My experience is that trace.exe and tracefmt.exe run best if run from the directory that contains the .tdf and .tff files.

Would it be better if the mapfile was run through c++filt?

**Comment by lerdmann** [comment]
@dryeo : ok in that case it works as it should. By the way, I now also get the error message you got when loading XUL.DLL code high. Guess the trace utility (or rather the DosDynamicTrace API) is just incapable of patching high memory addresses. But as you also found out, leaving the code in low memory is also not an option because of size restrictions.

@StevenLevine: yes c++filt would make things easier. But it would also be possible to just clip the names (after all it's only a trcust.exe problem on creating the formatting TFF file) Anyway, the sad but true fact that tracefmt.exe can only format minor codes <= 255 (and I am not talking about major trace code now) makes it largely useless for Dmitry, I guess. You would have to write your own formatting utility.

The whole tracing concept was not made for such huge things as XUL.DLL.

**Comment by lerdmann** [comment]
@dmik : I had a look at a couple of routines. And yes, none of these had a standard stack frame even with the debug version of XUL.DLL. However, that also does not matter if you'd follow the "dtrace buildtdf" approach. At least it would always be correct to assume that ESP is properly set on entry. Therefore you could always dump and display the passed parameters (how many that ever may be and how useful that would be ...).

**Comment by lerdmann** [comment]
What is the proper tool to strip debug info from the binary ? I tried "strip.exe" but it does not recognize the file format of XUL.DLL.

**Comment by dryeo** [comment]
From configure,
```
     STRIP=lxlite
     STRIP_FLAGS="/yua /ydd /yxd /ynl /anp /b- /cs+ /d /i- /ml1 /mr2 
/mf2 /r+ /u+ /x- /zs:0 /zx /zd"
```

**Comment by StevenLevine** [comment]
Another option is wstrip from OpenWatcom.  The syntax is

  wstrip xul.dll

FWIW, the antique strip.exe is documented to only work for a.out files.

Also, IMO all this discussion about formatting trace output is getting ahead of itself.  The current goal is to see if the strip output will help figure out what the code is doing that is causing firefox to peg the CPU at 100%.  The is what #248 is all about.

We are not going to know if OS/2 trace can even help until we get some output to look at.  I use the term some loosely.  We will probably need to use trspool to capture a couple a gigabytes of data and start looking for repeated call patterns or obvious loops.  None of this requires much formatted data.

**Comment by lerdmann** [comment]
wstrip tells me this:
'xul.dll.new' does not contain debugging information
but judging from the file size (compared to the 1. code memory object) I think it does.

lxlite tells me this with the flags given above:
FATAL: Internal error 203 at 00019BFB in lxLite version 1.3.3
I'll have to try a newer version of lxlite ...


The current problem is not formatting. The current problem is that DosDynamicTrace seems to be incapable of patching in INT3 instructions if the code resides in upper memory.
That's why we have to make the debug version of XUL.DLL "small enough" to fit into lower memory. My hope is that stripping debug info will help in making it "small enough".
If we get the code into lower memory then we can already see output in tracefmt.exe.

**Comment by lerdmann** [comment]
Ok, it worked with lxlite Version 1.3.9. It should now be possible to activate tracing.

**Comment by lerdmann** [comment]
This is the trace that I get before Firefox crashes (even though XUL.DLL is loaded into low memory):
[trace.zip](https://github.com/bitwiseworks/mozilla-os2/files/1800402/trace.zip)

Here the package, including xul.rpn:
[package.zip](https://github.com/bitwiseworks/mozilla-os2/files/1800403/package.zip)

**Comment by lerdmann** [comment]
End of trace before Firefox finally crashes:
[trace.zip](https://github.com/bitwiseworks/mozilla-os2/files/1800414/trace.zip)

The minor code 0x0657 therefore refers to "_moz_xmalloc" and I can see it being called very often.

**Comment by StevenLevine** [comment]
wstrip xul.dll works perfectly here.  You are probably using some old version of OpenWatcom.  Try using

  >wstrip
  Open Watcom Executable Strip Utility Version 2.0beta1 Limited Availability

Stripping the debug info will do nothing to change to memory usage when the kernel loads xul.dll.  What gave you this idea?

Is the problem patching the int3 into high memory or handling the breakpoint?

FWIW, is expected to see a lot of calls to _moz_xmalloc.  My limited testing using process dumps indicated something similar.  Do we have enough formatting available to know if we are in some sort of malloc retry loop?  Some things I noticed in the dump implied that the code was trying to allocate some sort of aligned buffer.

For example, one stack trace reported:

Finding from 0013b618 to 0013b718 by dword
13b61c: 1d299d12 = DosAllocMemEx + 62
13b64c: 0dbcab01 = js::Nursery::FreeMallocedBuffersTask::~FreeMallocedBuffersTask + 101
13b69c: 0dbced22 = js::gc::MapAlignedPages + 72
13b6ec: 0db9921c = js::gc::GCRuntime::pickChunk + 11C
13b71c: 0db12caf = js::gc::ArenaLists::allocateFromArena + 18F
13b730: 0dc877b0 = js::StackShape::trace + 0
13b77c: 0db12f2f = js::gc::GCRuntime::refillFreeListFromAnyThread + 3F

@lerdmann, are you sure you don't want an xul.map with demangedl labels?

**Comment by lerdmann** [comment]
1) I also think we are in some kind of malloc loop. Looking at it very briefly (did not have much time yet) it looked like _moz_xrealloc tried to repeatedly call _moz_malloc_size_of (or was it _moz_malloc_usable_size ?can't remember right now) and _moz_xmalloc. And it was NOT multiple invocations of _moz_xrealloc.
2) I will now run the map file through the c++filt utility so that we have more routines to look at. But I see 2 problems: there are just too many, far more than 65535 routines and then we still have the problem that gcc embeds read-only data in the code segment. I have no clue what symbols are pointing to code and what symbols are pointing to data (sometimes I have a suspicion but it surely is not enough to make a rule from it). The obvious problem is that overwriting the first byte of a potential read-only data pointer with 0xCC (INT3) is going to ask for trouble.
3) I did use the "wstrip" version you were stating above. It still did not work. I don't know why.
4) I thought that debugging info is always loaded into memory. Obviously I was wrong. Funny enough, stripping the info helped me in getting Firefox to start with the so stripped XUL.DLL. It only crashed after activating the trace and running for some time (I have the TRP file but I don't know if it is of much help).
We don't need the debugging info anyway if we use the RPN approach (but a non-optimized version of XUL.DLL is still better suited for the job at hand).
5) Any attempt to run "trace on xul" with the code loaded in high memory leads to an immediate refusal by trace.exe to do so with the error already mentioned "SYS0487: The specified address is incorrect." The help to SYS487 gives some very cryptic explanation that there is not enough room to store the selectors returned by DevHlp_AllocateGDTSelectors or that the specified address in DevHlp_PhysToGDTSelector goes past the end of possible memory. Whatever that means in this context.
Therefore patching did fail but even if it worked I don't yet know if there would be an error in triggering the tracepoint.

**Comment by StevenLevine** [comment]
You really need to build the TDF based on a subset of the symbols in the debug data, rather than the map file.  My current sense is that we are going to need to trace a number of static functions which are not in the map.

To deal with the 65K limit, one needs to apply some common sense and use the information we have to decide which symbols to trace.  This is how I built the map file that I use with pmdf to find all the code symbols on the stack.  In your case, there will be a lot of pruning.

To avoid trying to insert tracepoints in data, you need to use some common sense when building the map file.  Once you convert the symbols with c++filt, it will be more obvious what is data and what is code and the data symbols can be pruned from the map file.  We certainly don't need to try to set tracepoint in some vtable that happens to have a symbolic name.

The error seems to imply that the tracing support code is not fully 32-bit capable.  Best I can tell the sys0487 comes directly from:

  #define ERROR_INVALID_ADDRESS   487     /* MSG%INVALID_ADDRESS */

which I read to mean that the API does not support the supplied address.

FWIW, I've been running the beta xul.dll, with debug data intact, loading in low memory since it appeared because I forgot to mark it to load high.  When we get some free time, we might want to try to isolate what makes your system different.  Just to be sure, I retested wstrip and it continues to work fine.  I even rename xul.dll to xul.dll.new just inc and this too worked fine.

**Comment by lerdmann** [comment]
0) after loading "beta xul.dll with debug data intact", have you also tried to enable tracing with "trace on xul" ? That's the interesting bit ...
1) How do I examine the debug symbols in the debug info rather than the ones in the map file ? Of course, if I knew routine names I wanted to look at beforehand, I could try the "trcust: from TSF to TDF" instead of the "dtrace: from RPN to TDF" approach but currently I would not even know what to look at (apart from what I find in the MAP file).
2) I'd appreciate if there were a switch/pragma to gcc.exe to tell it to put read-only data (const, vtables, etc.) into its own memory object (and that's what icc.exe does as a default). That way it would become a lot easier to separate code from data. But I am unfamiliar with gcc.

**Comment by lerdmann** [comment]
I now tried "c++filt" on the map file:
this demangles ok: __ZN11stagefright8MetaDataD2Ev -> stagefright::MetaData::~MetaData()

In fact, most methods demangle ok. However, as an example, this one does not: 

__ZNK11stagefright12SortedVectorINS_16key_value_pair_tIjNS_8MetaData10typed_dataEEEE12do_constructEPvj$w$dlRia1FTGn7BZYC71

Is there a trick ? Or, if things do not demangle, can I assume that it is data or a vtable (in which case I'd need to remove it anyways) ?

**Comment by dmik** [comment]
@lerdmann the trick is the `$w$XXXXXXX` suffix added by the EMX weak linker. If you remove it, it will demangle fine (provided that the version of c++filt matches the version of the compiler).

**Comment by lerdmann** [comment]
Thanks for the info. I did as you said and yes, it did demangle. However, it's not going to help anyways.
"dtrace.exe buildtdf xul.rpn" traps with let's say more than 0x2000 (8192) minor trace codes.
"trcust.exe xul.tsf" traps with about more than 0xFF00 (65280) minor trace codes.

These tools are just not created for this amount of data. It's a hopeless case.

**Comment by dmik** [comment]
BTW, I've built Firefox with `-fno-omit-stackframe -fno-inline` and with disabled optimization. I got XUL.DLL as big as 660M instead of 440M and it still seems to load and work.

Uploaded it as http://rpm.netlabs.org/test/x4.7z (and the map file is in x4m.7z) for everyone to play around. Perhaps, this one will work better with PDUMP as all stack frames should be there.

As for TRACE, I also tend to give up on that in case of XUL.

**Comment by dspiatkowski** [comment]
Can we still lxlite that XUL, or must it be run as-is?

I run the following lxlite options:

/yua /ydd /yxd /ynl /anp /b- /cs+ /d /i- /ml1 /mr2 /mf2 /r+ /u+ /x- /zs:0  
/zx /zd

**Comment by dryeo** [comment]
On 03/15/18 06:45 PM, Dariusz Piatkowski wrote:
> Can we still lxlite that XUL, or must it be run as-is?

Why not? Of course that leads to why?

**Comment by lerdmann** [comment]
1) for a normal user there is no reason whatsoever to use the rebuilt XUL.DLL. Just the opposite is true: the loss of optimiziation is clearly noticeable. But the rebuilt XUL.DLL will make it possible for Dmitry to follow the call chain and ultimately to find the origin of a failure.
2) I did try to create a TDF file from both, the unstripped and also the stripped version of the latest XUL.DLL that Dmitry provided. As I said, it's a hopeless case. If the number of minor trace codes exceeds some maximum of about 2000 then the system will blow as soon as you enable tracing on XUL.DLL.

**Comment by dmik** [comment]
@dspiatkowski it's a special build for debugging purposes. It makes no sense to lxlite it nor to use it in place of the x3 build (or an RPM build of Firefox) for normal browsing — w/o optimization, it's damn slow (and makes no difference compared to x3 function wise).

**Comment by dmik** [comment]
I'm closing this as a no way to go.

**Comment by dspiatkowski** [comment]
Hi Dimitriy,

On Fri, 16 Mar 2018 11:08:30 +0000 (UTC) Dmitriy Kuminov wrote:
>
> @dspiatkowski it's a special build for debugging purposes. It makes no  
> sense to lxlite it nor to
> use it in place of the x3 build (or an RPM build of Firefox) for normal  
> browsing - w/o
> optimization, it's damn slow (and makes no difference compared to x3  
> function wise).

OK, I understand the intent of this build (having kept up with the list  
conversation, although some of the details are obviously beyond my level of  
experience and understanding).

So why am I posing the question?

Well, my intent was to try to contribute some debug info. I was going to  
deploy this setup and use the browser in as normal of a fashion as possible  
during the debug session. At least attempting to capture the specific  
use-cases where I see the behaviour we are trying to address on my machine  
- sort of what I think Dave Yeo was doing. Therefore, I'm trying to  
understand if this is feasible, but given that FF is incredibly memory  
hungry I didn't want that issue to be impacting the results.

Given the status of this issue and the challenges we have, is there even  
any point to trying to attempt such a debug session?

**Comment by dmik** [comment]
@dspiatkowski thanks for your intent, but this isn't really necessary. This way, you won't see anything interesting that could help.
