### ISSUE TITLE
Some gifs cause high CPU usage.

### ISSUE THREAD

**Issue by dryeo** [bitwiseworks/mozilla-os2#277]
Some gif files seem to cause erratic high CPU usage. One example is https://mantis.arcanoae.com/images/priority_normal.gif which I'll attempt to attach. Drop it on an empty tab and watch the CPU meter

**Comment by dryeo** [comment]
Had to boot to Linux to attach
![priority_normal](https://user-images.githubusercontent.com/399667/49136463-7f579180-f29e-11e8-8b2a-46d02e43ac7d.gif)

**Comment by dryeo** [comment]
This regression seems to have happened on updating to 45.9 as the last 45.5 release doesn't show the high CPU usage.

**Comment by dryeo** [comment]
This is actually a side affect of https://github.com/bitwiseworks/mozilla-os2/commit/d010d843a7117f64f870f1979cd120b5c886f10a, [OS/2] Temporarily disable usage of Vsync timers by default. Changing the pref to -1 fixes the issue, but of course causes other issues as described in #208

**Comment by dmik** [comment]
Thanks for the report. Yes, you found the right cause of this problem. Although I wouldn't call it a side effect of that commit. It's not the commit that is guilty, it's the whole 49 branch where they seriously redesigned the renderer pipeline and some other things related to timers and event processing taking the capabilities of the modern hardware into account. It seems that we lack support for this modern hardware in a few places (not a surprise) which resulted in performance degradation. There is no easy solution to that problem as we can't simply restore what was before.

Note that manipulating with `layout.frame_rate` is a compromise. It solves one problem but brings a bunch of others. It's best to experiment with its values to find out which one works best for your hardware and software configuration. Closing this.

**Comment by dspiatkowski** [comment]
Hi Dmitriy and team!

On Mon, 03 Dec 2018 16:05:08 +0000 (UTC) Dmitriy Kuminov wrote:
>
> Thanks for the report. Yes, you found the right cause of this problem.  
> Although I wouldn't call it
> a side effect of that commit. It's not the commit that is guilty, it's  
> the whole 49 branch where
> they seriously redesigned the renderer pipeline and some other things  
> related to timers and
> event processing taking the capabilities of the modern hardware into  
> account. It seems that we
> lack support for this modern hardware in a few places (not a surprise)  
> which resulted in
> performance degradation. There is no easy solution to that problem as we  
> can't simply restore
> what was before.
>
> Note that manipulating with `layout.frame_rate` is a compromise. It  
> solves one problem but
> brings a bunch of others. It's best to experiment with its values to find  
> out which one works
> best for your hardware and software configuration. Closing this.

I am curious about an option I thought we had: Lars created a preliminary  
driver to provide the hardware sync signal. This came out of video driver  
discussion, and I specifically remember looking at the SNAP SDK to note  
that APIs existed that appeared to provide this type of capability. Lars'  
work is still out there, although we apparently never went anywhere with  
this approach.

Would it not be possible for us to at lest utilize that approach to deal  
with a very single issue that is being widely recognized as impacting just  
about (in fact everyone I think) using our latest FF release? That being  
the impact of the GIF image settings which Dave reported.

I have spent considerable amount of time trying various layout.frame_rate  
settings, much of it during our FF debugging sessions. What I have right  
now somewhat works (about 100% single core utilization spread across 5  
cores, so enough "spare compute capacity" left to go around for other  
uses). However, it certainly seems like we are seeing more and more of this  
symptom.

Anyways, just bringing up that old thread up for some air since it seemed  
like a promising approach back when we were discussing it.

Thanks everyone,
-Dariusz

**Comment by dryeo** [comment]
This issue is finally being fixed/worked around upstream, mostly by replacing all GIF's with PNG's. Seems the culprit is Gimp, which always exports GIF's with a non-zero delay leading Mozilla to handle them as single frame animated GIF's leading to a performance hit on all platforms but obviously much worse on ours due to then using hardware vsync.

**Comment by dryeo** [comment]
s/then//them/
