### ISSUE TITLE
Menu option Tools->"Clear recent history" does not work

### ISSUE THREAD

**Issue by rwklein** [bitwiseworks/mozilla-os2#32]
The menu loads. However I can not select any of the checkboxes...

**Comment by SilvanScherrer** [comment]
did anyone test, if this is still true with latest FFox 24 beta?

**Comment by guzzi-g5** [comment]
Still the same

**Comment by dmik** [comment]
What I found so far: this dialog is done in JS as well now (look for `sanitize.js` and `sanitizeDialog.js` and their `.xul` and `.css` counterparts). And somehow all the check boxes become disabled on OS/2 (can't be clicked). Not clear why so far.

**Comment by dmik** [comment]
No, it doesn't seem to be just that. They are not disabled. AFAICS, it is designed so that when the user hits a check box bound to a preference a signal is sent that changes the value of the preference and the check box appearance is changed only when the value change signal from the preference engine comes back. For some reason, the check box doesn't seem to change its preference here and hence no signal carrying the changed value is emitted. Looking through it.

**Comment by dmik** [comment]
No, it doesn't have anything to do with preference synchronization. The XUL corresponding to this dialog uses `<listbox>` and `<listitem>` to represent the list of history-like entities to clear. Besides those, there are also `<richlistbox>` and `<richlistitem>` used in many other places (e.g. in preferences dialogs). If I change `<listbox>/<listitem>` to `<richlistbox>/<richlistitem>` then everything works: both the check box appearance and the functionality (the history gets cleared according to the settings).

This suggests us that the widget implementation of the `<listitem>` XUL element is somehow broken on OS/2. It's interesting that there is only one real dialog that uses `<listitem>` (besides the test stuff) — the "clear history" one. That explains why we haven't seen this problem before. It may be a challenge to find the corresponding code for that XUL element.

**Comment by dmik** [comment]
JFYI, this is how it looks with my hack:

![2015-03-04 1 27 05](https://cloud.githubusercontent.com/assets/900726/6473944/00b6cca2-c20e-11e4-9453-bd5b92925ebe.png)

And the original view:

![2015-03-04 1 27 54](https://cloud.githubusercontent.com/assets/900726/6473950/0db21a7e-c20e-11e4-94e6-6198b90d5741.png)

Another interesting thing is that the defect relates only to the visual implementation. I.e the state of the check box is correctly changed when you click it with the mouse, only it doesn't get properly displayed. Maybe they use some pixmap fro the check mark and this pixmap is not found on OS/2.

**Comment by dmik** [comment]
I found a way to fix it, see 512c085162e2133575c957c9392dadf1229661a4 for details I basically took the necessary lines this from the OS X theme.

The missing code was not a problem on Windows and Linux because there it seems that check boxes are painted using native system UI primitives rather than CSS. But on OS/2 almost everything painted using CSS so there was simply no code to draw these check boxes.

Now the dialog looks like this which is more than enough I think:

![2015-03-04 4 10 48](https://cloud.githubusercontent.com/assets/900726/6476471/2c6b404e-c227-11e4-97ea-c1e5d4cc4939.png)
