### ISSUE TITLE
Native plugins freezes system

### ISSUE THREAD

**Issue by an64** [bitwiseworks/mozilla-os2#47]
I have two native plugins , warpvision ( http://hobbes.nmsu.edu/download/pub/os2/apps/mmedia/video/players/wvgui_20070625.zip , can simply open .avi in player window, embedded in browser) and djvu ( http://hobbes.nmsu.edu/download/pub/os2/apps/internet/www/browser/npdjvu_093.zip ).
Both freezing gui and cause 100% cpu load, killing plugin-container.exe does not help, only with firefox.exe.

These plugins not so important for me, but may be helpful to you to debug some problems without  involving  complex odin system

**Comment by dryeo** [comment]
I'm still seeing 100% CPU when clicking on a zip file, which invokes npawgbin.dll which in turn invokes awget. Once again it is plugin-container.exe hogging the CPU and setting dom.ipc.plugins.enabled to false fixes the problem.
Really I think that ipc.plugins should be disabled for all plugins instead of just Flash.

**Comment by dmik** [comment]
Well, yes, until we fix IPC. But I thought I disabled it by default. I will recheck.

**Comment by dmik** [comment]
I"m closing this in favor of #106 as that one describes the main problem.
