### ISSUE TITLE
Firefox 24.8.1 release creates BAD thumbnails

### ISSUE THREAD

**Issue by dspiatkowski** [bitwiseworks/mozilla-os2#84]
I had just moved to 24.8.1 (Firefox 24.8.1 Beta 2 (2014-09-26)) release from my previous version (Firefox 17.0.11 (dryeo release, 2014-06-14)).

In the process of getting my profile ready for the upgrade (cleanup, backup, etc) I discovered that the thumbnails directory (profile) was some 1.2Gig in size. Researched this topic, discovered that I could purge all these images, reclaimed a pile of disk scape, was happy.

I then upgraded to 24.8.1 beta 2 and found out that the 'newtab' setup, which usually shows 9 thumbnails in my configuration, was only showing BLANK thumbnails. I reviewed the contents of the thumbnails directory (G:\apps\tcpip\mozilla.org\userprofiles\Mozilla\Firefox\Profiles\q5xd2gmv.default\thumbnails\*.png) and found that while there were some 70 PNG images present each and every one of them was invalid.

Attempting to open them with PMVIew (3.75) shows the following error message "...Unrecognized file format...", so it appears that 24.8.1 is somehow generating BAD PNG thumbnail images and therefore the newtab is unable to display them.

This may be similar to previously reported issue "Home Page issues #33", however that user really wasn't clear about the true problem being reported, at least I could not determine if it was the same problem I was facing or whether it was an issue with blank thumbnails because the profile directory was purged.

Let me know what you need, I can upload sample bad PNG thumbnail image next...

Thanks!

**Comment by dmik** [comment]
I can confirm that .png files in that directory are broken. This may be due to inappropriate text mode file operations on binary PNG data (as Silvan guessed). I will check all this.

**Comment by dmik** [comment]
It was a usual CRLF (O_BINARY / O_TEXT) problem indeed, but well hidden. The thumbnail processing code is written in JS now and JS uses its own abstraction layer that does file I/O (what a great idea!) defined in `toolkit/components/osfile`. On OS/2 this layer uses the `open` LIBC API to open files and this API uses O_TEXT mode by default.

In 5c96cec8893991c4de4e0b4ac6bcd202e5ee2dea I extended the JS code to support O_TEXT and O_BINARY and I made O_BINARY the default within this JS layer and thumbnails now work for me.

We could use the `-Zbin-files` linker option to make O_BINARY a global default in LIBC but I dislike this idea because it will break backward compatibility (e.g. many files in the profile directory use CRLF) and may other unexpected side effects. So we will have to fix it on step-by-step basis, as long as we find new problems.

BTW, this fix may also fix other issues. We need to check through them. Note that this code is new since FF 17 and that's because it worked there. Now, they move more and more functionality from C to JS so we should expect more regressions in that area.

**Comment by dspiatkowski** [comment]
Gentlemen, happy to report that in FF38.8.0 this issue is no longer present. The 'thumbnails' directory shows correct image files.

So far I have been running FF38.8.0 only for a few days, but the directory size is reasonable as well, meaning, I no longer appear to be experiencing this exponential growth in thumbnails generation.

If you wish you can close this ticket, or if you want I can continue to test this in future releases.

Thanks,
-Dariusz
